def plot_gradflow_v1(named_parameters):
    ...

def plot_gradflow_v2(named_parameters):
    ...

    Usage: Plug this function in Trainer class after loss.backwards() as
                                             ...

