class LossLog():
    ...

    def __init__(self, plotdir=None, xlabel='Epoch', ylabel='Loss', title=None, filename=None, logdict=None, lom='min'):
        ...

    def assign(self, key, value):
        ...

    def add(self, key, value):
        ...

    def get(self, key=None):
        ...

    def updir(self, plotdir=None):
        ...

    def plot(self, x=None):
        ...

    def judge(self, key, n1=50, n2=10):
        ...


