class PhaseConv1d(th.nn.Module):
    ...

class PhaseConv2d(th.nn.Module):
    ...

class ComplexPhaseConv1d(th.nn.Module):
    ...

class ComplexPhaseConv2d(th.nn.Module):
    ...

class PhaseConvTranspose1d(th.nn.Module):
    ...

class PhaseConvTranspose2d(th.nn.Module):
    ...

class ComplexPhaseConvTranspose1d(th.nn.Module):
    ...

class ComplexPhaseConvTranspose2d(th.nn.Module):

