class MetaDataLoader:
    ...

    def __init__(self, x, y, bstask, nway=1, kshot=1, kquery=1, sfltask=False, sflpoint=False, dsname='train'):
        ...

    def next(self):
        ...

    def __len__(self):
        ...


